# Generated by Django 2.2.1 on 2019-06-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190528_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crime',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
